import React,{useEffect,useState} from 'react'
import {customerApi,postJson} from '../lib/customerApi.js'

const serviceLabels={inactive:'غير مفعلة',trial_pending:'التجربة بانتظار الموافقة',trial_active:'تجربة مجانية',trial_expired:'انتهت التجربة',active:'نشطة',grace:'فترة سماح',credit:'آجل',suspended:'موقوفة',cancelled:'ملغاة'}
const payStatus={pending_admin:'بانتظار الإدارة',approved:'مقبول',rejected:'مرفوض'}
function StatusCard({title,value,sub,tone=''}){return <div className={`account-stat ${tone}`}><small>{title}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}
async function copyText(t){
  try{await navigator.clipboard.writeText(t)}catch{const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}
}

export default function CustomerAccount({navigate,refreshAuth}){
 const [data,setData]=useState(null),[config,setConfig]=useState(null),[plans,setPlans]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[msg,setMsg]=useState(''),[action,setAction]=useState('')
 const [verifyScript,setVerifyScript]=useState(''),[setupScript,setSetupScript]=useState('')
 const [pay,setPay]=useState({depositor_name:'',transaction_number:'',amount:'',deposit_date:'',message:'',invoice_id:''}),[receipt,setReceipt]=useState(null)
 async function load(){setLoading(true);setError('');try{const [me,cfg,pl]=await Promise.all([customerApi('/me'),customerApi('/config'),customerApi('/plans')]);setData(me);setConfig(cfg);setPlans(pl);await refreshAuth?.()}catch(e){if(e.status===401){await refreshAuth?.();navigate('/customer-login');return}setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function logout(){try{await postJson('/logout',{})}catch{}await refreshAuth?.();navigate('/')}
 async function act(name,fn){setAction(name);setError('');setMsg('');try{await fn();await load()}catch(e){setError(e.message)}finally{setAction('') }}
 async function resendEmail(){await act('email',async()=>{const r=await postJson('/email/resend',{email:data.customer.email});setMsg(r.email_sent?'تم إرسال رمز جديد إلى بريدك.':'تعذر إرسال البريد. تواصل مع الإدارة.')})}
 async function createOrder(plan){await act(`plan-${plan.id}`,async()=>{const r=await postJson('/order',{plan_id:plan.id,notes:''});setMsg(`تم إنشاء الطلب والفاتورة ${r.invoice_no}. أرسل تأكيد الدفع بعد الإيداع.`)})}
 async function generateVerify(){await act('verify-router',async()=>{const r=await postJson('/router/verification-token',{});setVerifyScript(r.script);setMsg('انسخ الكود وشغّله مرة واحدة في Terminal داخل MikroTik ثم اضغط تحديث الحالة.')})}
 async function requestTrial(){await act('trial',async()=>{await postJson('/trial/request',{});setMsg('تم إرسال طلب التجربة للإدارة، وسيصلك بريد تلقائي عند القبول أو الرفض.')})}
 async function getSetup(){await act('setup',async()=>{const r=await customerApi('/router/setup-script');setSetupScript(r.script);setMsg('تم تجهيز كود اتصال VPN الخاص بحسابك.')})}
 async function submitPayment(e){e.preventDefault();setAction('payment');setError('');setMsg('');try{const fd=new FormData();for(const [k,v] of Object.entries(pay)){if(v!==''&&v!=null)fd.append(k,v)}if(receipt)fd.append('receipt',receipt);await customerApi('/payment-confirmations',{method:'POST',body:fd});setPay({depositor_name:'',transaction_number:'',amount:'',deposit_date:'',message:'',invoice_id:''});setReceipt(null);setMsg('تم إرسال تأكيد الدفع إلى الإدارة للمراجعة، وسيصلك بريد تلقائي عند القبول أو الرفض.');await load()}catch(e){setError(e.message)}finally{setAction('') }}
 if(loading)return <section className="auth-page"><div className="container"><div className="auth-card"><h2>جارٍ تحميل حسابك...</h2></div></div></section>
 if(error&&!data)return <section className="auth-page"><div className="container"><div className="auth-card"><h2>تعذر تحميل الحساب</h2><div className="form-error">{error}</div><button className="btn btn-ghost" onClick={load}>إعادة المحاولة</button></div></div></section>
 const c=data.customer,svc=data.service||{},router=data.router||{},trial=data.trial||{},sub=data.subscription||{},finance=data.financial||{}
 const outstanding=(data.invoices||[]).filter(x=>['pending','partial','credit','overdue'].includes(x.status))
 const openOrder=(data.orders||[]).find(x=>['pending_payment','pending_admin'].includes(x.status))
 const canTrial=!!trial.can_request
 const endpoints=router.access_endpoints||[]
 const devicePortal=router.device_portal||null
 return <section className="account-page"><div className="container">
  <div className="account-head"><div><span className="eyebrow">بوابة المشترك</span><h1>{c.network_name||c.full_name}</h1><p>{c.email}</p></div><div className="actions"><button className="btn btn-ghost" onClick={load}>تحديث</button><button className="btn btn-ghost" onClick={logout}>تسجيل الخروج</button></div></div>
  {msg&&<div className="notice-box good">{msg}</div>}{error&&<div className="form-error account-error">{error}</div>}
  {!c.email_verified&&<div className="account-panel verify-alert"><div><span className="eyebrow">مطلوب قبل المتابعة</span><h2>أكد بريدك الإلكتروني</h2><p>لن تستطيع طلب الباقة أو ربط MikroTik أو التجربة قبل تأكيد البريد.</p></div><div className="actions"><button className="btn btn-primary" onClick={()=>navigate(`/verify-email?email=${encodeURIComponent(c.email)}`)}>إدخال رمز التحقق</button><button className="btn btn-ghost" disabled={action==='email'} onClick={resendEmail}>إرسال رمز جديد</button></div></div>}
  <div className="account-stats"><StatusCard title="حالة الخدمة" value={serviceLabels[svc.status]||svc.status||'غير مفعلة'} sub={svc.suspend_at?`موعد الإيقاف: ${svc.suspend_at}`:''} tone={['active','trial_active','grace','credit'].includes(svc.status)?'good':''}/><StatusCard title={finance.status==='credit'?'رصيد دائن':'الرصيد المستحق'} value={`${finance.status==='credit'?(finance.credit_balance||'0.00'):(finance.balance_due||'0.00')} ${finance.currency||config?.payment?.currency||''}`} sub={finance.status==='clear'?'الحساب مسوّى':finance.status==='credit'?'رصيد لصالحك محفوظ في الحساب':'يوجد رصيد مستحق'} tone={finance.status==='credit'?'good':''}/><StatusCard title="MikroTik" value={router.serial_verified?'تم التحقق':'بانتظار الربط'} sub={router.serial?`${router.model||''} · ${router.serial}`:'Serial يقرأ من الراوتر نفسه'} tone={router.serial_verified?'good':''}/><StatusCard title="Remote VPN" value={router.provisioned?(router.remote_access_enabled?'مفعّل':'موقوف'):'لم ينشأ بعد'} sub={router.vpn_ip?`VPN IP: ${router.vpn_ip}`:'يُنشأ بعد موافقة التجربة أو الدفع'} tone={router.remote_access_enabled?'good':''}/></div>

  {router.provisioned&&<div className="account-panel access-panel">
    <div className="panel-title"><div><span className="eyebrow">بيانات الوصول</span><h2>عناوين الدخول عن بُعد</h2></div><span className={`access-state ${router.remote_access_enabled?'online':'offline'}`}>{router.remote_access_enabled?'الخدمة مفعلة':'الخدمة موقوفة'}</span></div>
    <p>هذه هي العناوين والمنافذ المخصصة لشبكتك. انسخ أي عنوان واستخدمه من خارج الشبكة حسب الخدمة.</p>
    {endpoints.length?<div className="endpoint-grid">{endpoints.map(ep=><div className="endpoint-card" key={ep.service}><div><span>{ep.label}</span><strong className="mono" dir="ltr">{ep.address}</strong>{ep.url&&<small className="mono" dir="ltr">{ep.url}</small>}</div><div className="endpoint-actions"><button className="btn btn-ghost btn-small" onClick={async()=>{await copyText(ep.url||ep.address);setMsg(`تم نسخ عنوان ${ep.label}`)}}>نسخ</button>{ep.url&&<a className="btn btn-ghost btn-small" href={ep.url} target="_blank" rel="noreferrer">فتح</a>}</div></div>)}</div>:<div className="empty-customer-state">لم يتم تخصيص منافذ وصول فعالة بعد.</div>}
    {router.remote_access_host&&<div className="host-summary"><span>Remote Host</span><strong className="mono" dir="ltr">{router.remote_access_host}</strong><button className="btn btn-ghost btn-small" onClick={async()=>{await copyText(router.remote_access_host);setMsg('تم نسخ اسم المضيف')}}>نسخ</button></div>}
  </div>}

  {devicePortal&&<div className="account-panel portal-access-card">
    <div><span className="eyebrow">لوحة إدارة الأجهزة</span><h2>لوحة العميل الخاصة بشبكتك</h2><p>استخدم هذه اللوحة لإدارة الأجهزة الداخلية والوصول إليها حسب الصلاحيات التي منحتها الإدارة.</p></div>
    <div className="portal-access-details"><span>اسم المستخدم <b className="mono" dir="ltr">{devicePortal.username}</b></span><span>الأجهزة المسموحة <b>{devicePortal.max_devices}</b></span><a className="btn btn-primary" href={devicePortal.url} target="_blank" rel="noreferrer">فتح لوحة الأجهزة</a></div>
  </div>}

  {c.email_verified&&<div className="account-grid">
   <article className="account-panel"><span className="eyebrow">الخطوة 1</span><h2>اختيار الباقة</h2>{plans.length?<div className="plan-mini-grid">{plans.map(p=><div className={`plan-mini ${sub.plan_name===p.name?'selected':''}`} key={p.id}><b>{p.name}</b><strong>{p.price} {p.currency}</strong><small>{p.billing_months} شهر · {p.trial_allowed?'تشمل أهلية التجربة':'بدون تجربة'}</small><button className="btn btn-primary" disabled={!!openOrder||!!sub.plan_name||action===`plan-${p.id}`} onClick={()=>createOrder(p)}>{sub.plan_name===p.name?'الباقة الحالية':openOrder?'يوجد طلب مفتوح':'اختيار وإنشاء فاتورة'}</button></div>)}</div>:<div className="empty-customer-state">لا توجد باقات متاحة حاليًا.</div>}</article>
   <article className="account-panel"><span className="eyebrow">الخطوة 2</span><h2>التحقق من MikroTik</h2><p>نقرأ Serial Number الحقيقي من جهازك لمنع تكرار التجربة. لا تكتب السيريال يدويًا.</p>{router.serial_verified?<div className="notice-box good">تم التحقق: <b>{router.serial}</b> · {router.model||router.board_name||''}</div>:<><button className="btn btn-primary" disabled={action==='verify-router'} onClick={generateVerify}>إنشاء كود التحقق</button>{verifyScript&&<div className="code-box"><textarea readOnly value={verifyScript}/><button className="btn btn-ghost" onClick={()=>copyText(verifyScript)}>نسخ الكود</button></div>}</>}</article>
  </div>}

  {c.email_verified&&<div className="account-grid">
   <article className="account-panel"><div className="panel-title"><div><span className="eyebrow">الخطوة 3</span><h2>التجربة المجانية</h2></div><span className="trial-days">{trial.default_days||5} أيام</span></div><p>تبدأ من لحظة موافقة الإدارة ولا تخصم من الاشتراك المدفوع. الأهلية مرتبطة بالبريد والـSerial.</p>{trial.status==='active'&&<div className="notice-box good">التجربة فعالة حتى {trial.ends_at}</div>}{trial.status==='pending_admin'&&<div className="notice-box">طلب التجربة بانتظار موافقة الإدارة. ستصلك النتيجة عبر البريد.</div>}{!canTrial&&trial.eligibility_reasons?.length>0&&<div className="notice-box">{trial.eligibility_reasons.join(' · ')}</div>}{canTrial&&<button className="btn btn-primary" disabled={action==='trial'} onClick={requestTrial}>طلب تجربة مجانية</button>}</article>
   <article className="account-panel"><span className="eyebrow">كود اتصال VPN</span><h2>إعداد MikroTik Remote VPN</h2><p>بعد قبول التجربة أو تأكيد الدفع ينشئ السيرفر حساب VPN ثابتًا. الكود المعروض هنا خاص باتصال VPN فقط ولا يغيّر المستخدمين أو خدمات MikroTik.</p>{router.provisioned?<><button className="btn btn-primary" disabled={action==='setup'} onClick={getSetup}>عرض كود اتصال VPN</button>{setupScript&&<div className="code-box"><textarea readOnly value={setupScript}/><button className="btn btn-ghost" onClick={()=>copyText(setupScript)}>نسخ الكود</button></div>}</>:<div className="notice-box">لم يتم إنشاء VPN بعد. انتظر موافقة الإدارة على التجربة أو اعتماد أول دفعة.</div>}{svc.network_last_error&&<div className="form-error">مشكلة مزامنة الشبكة: {svc.network_last_error}</div>}</article>
  </div>}

  <div className="account-grid lower">
   <article className="account-panel"><span className="eyebrow">الدفع المعتمد</span><h2>{config?.payment?.method||'الكريمي'} — {config?.payment?.account_label||'الحساب السعودي'}</h2><div className="bank-account-card inline"><small>رقم الحساب</small><strong className="mono">{config?.payment?.account_number||'3027149935'}</strong></div><p>بعد الإيداع أرسل اسم المودع ورقم العملية. ستصلك رسالة بريد تلقائية عند اعتماد العملية أو رفضها.</p><form className="payment-form" onSubmit={submitPayment}>{outstanding.length>0&&<label>الفاتورة<select value={pay.invoice_id} onChange={e=>setPay(x=>({...x,invoice_id:e.target.value}))}><option value="">الأقدم تلقائيًا</option>{outstanding.map(i=><option key={i.id} value={i.id}>{i.invoice_no} — {i.balance_due} {i.currency}</option>)}</select></label>}<label>اسم المودع<input required value={pay.depositor_name} onChange={e=>setPay(x=>({...x,depositor_name:e.target.value}))}/></label><label>رقم العملية<input required value={pay.transaction_number} onChange={e=>setPay(x=>({...x,transaction_number:e.target.value}))}/></label><div className="form-two"><label>المبلغ<input required inputMode="decimal" value={pay.amount} onChange={e=>setPay(x=>({...x,amount:e.target.value}))}/></label><label>تاريخ الإيداع<input required type="date" value={pay.deposit_date} onChange={e=>setPay(x=>({...x,deposit_date:e.target.value}))}/></label></div><label>رسالة للإدارة<textarea value={pay.message} onChange={e=>setPay(x=>({...x,message:e.target.value}))}/></label><label>صورة الإيصال — اختياري<input type="file" accept="image/*,.pdf" onChange={e=>setReceipt(e.target.files?.[0]||null)}/></label><button className="btn btn-primary" disabled={action==='payment'}>إرسال تأكيد الدفع</button></form></article>
   <article className="account-panel"><span className="eyebrow">الفواتير والمتابعة</span><h2>حالة الحساب</h2><div className="customer-events">{(data.invoices||[]).length?(data.invoices||[]).map(i=><div className="customer-event" key={i.id}><div><b>{i.invoice_no}</b><span>{i.status}</span></div><div><strong>{i.balance_due} {i.currency}</strong><small>{i.due_date}</small></div></div>):<div className="empty-customer-state">لا توجد فواتير حتى الآن.</div>}</div><h3>تأكيدات الدفع</h3><div className="customer-events">{(data.payment_confirmations||[]).length?(data.payment_confirmations||[]).slice(0,8).map(x=><div className="customer-event" key={x.id}><div><b>{x.transaction_number}</b><span>{x.depositor_name}</span></div><div><strong>{x.amount} {x.currency}</strong><small className={`status-pill ${x.status}`}>{payStatus[x.status]||x.status}</small></div></div>):<div className="empty-customer-state">لا توجد تأكيدات دفع.</div>}</div></article>
  </div>
 </div></section>
}
