import React from 'react'
import AppMockup from '../components/AppMockup.jsx'
import SectionTitle from '../components/SectionTitle.jsx'
import TutorialCard from '../components/TutorialCard.jsx'
import { features, stats, whatsapp, teamServices, speedMethods, studio } from '../data/content.js'
import Icon from '../components/Icon.jsx'
import { tutorials, tutorialCategories } from '../data/tutorials.js'

function Hero({navigate}){const h=studio.hero;const media=studio.mediaSlots||{};return <section className="hero"><div className="hero-grid-bg"/><div className="orb orb-1"/><div className="orb orb-2"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><span className="dot"/> {h.eyebrow}</span><h1>{h.titleLine1}<br/><span>{h.titleAccent}</span></h1><p>{h.description}</p><div className="hero-buttons"><button className="btn btn-primary" onClick={()=>navigate(h.primaryPath)}>{h.primaryText}</button><button className="btn btn-ghost" onClick={()=>navigate(h.secondaryPath)}>{h.secondaryText} <span>←</span></button></div><div className="hero-trust">{h.trust.map(x=><span key={x}>✓ {x}</span>)}</div></div>{media.heroVisualMode==='image'&&media.heroVisual?<div className="hero-real-visual"><div className="hero-real-phone"><img src={media.heroVisual} alt={media.heroVisualAlt||'OnStar'}/></div></div>:<AppMockup/>}</div></section>}
function Brand(){return <section className="brand-strip"><div className="container strip-items">{studio.brandStrip.map(x=><span key={x}>{x}</span>)}</div></section>}
function Features(){return <section className="section"><div className="container"><SectionTitle eyebrow="منصة واحدة" title="كل أدواتك الأساسية في مكان واحد" text="صمّم الصفحة، راقب الشبكة، افحص الأجهزة، ونظّم أعمالك اليومية من واجهة موحدة." center/><div className="feature-grid">{features.map((f,i)=><article className="feature-card" key={f.title}><div className="icon-box app-icon"><img src={f.icon} alt=""/></div><h3>{f.title}</h3><p>{f.text}</p><span className="feature-no">0{i+1}</span></article>)}</div></div></section>}
function Speed(){return <section className="section speed-showcase"><div className="container"><SectionTitle eyebrow="ميزة بارزة في OnStar" title="خمس طرق لتحديد السرعة — بدومين أو بدون دومين" text="بدل إجبارك على طريقة واحدة، يتيح OnStar اختيار أسلوب تحديد السرعة المناسب لبنية شبكتك، ثم إدارة الإعداد من الهاتف." center/><div className="speed-methods-grid">{speedMethods.map((m,i)=><article key={m.title}><span>0{i+1}</span><h3>{m.title}</h3><p>{m.text}</p></article>)}</div><div className="speed-switch-panel"><div><span className="eyebrow">مرونة الصفحة</span><h3>حوّل الصفحة من تحديد سرعة إلى بدون تحديد سرعة — والعكس</h3><p>في أي وقت، ومن داخل إعدادات التطبيق، تستطيع تغيير نمط الصفحة بين وجود اختيار السرعة وعدم وجوده ثم العودة للوضع الآخر عند الحاجة.</p></div><div className="switch-visual"><b>بدون تحديد سرعة</b><span className="switch-track"><i/></span><b>تحديد السرعة مفعّل</b></div></div></div></section>}
function Services({navigate}){return <section className="section team-services-preview"><div className="container"><div className="section-split-head"><SectionTitle eyebrow="خدمات الفريق البرمجي" title="خدمات فنية مستقلة عن التطبيق" text="إلى جانب OnStar، يقدم الفريق خدمات تنفيذ وبرمجة للشبكات. هذه الخدمات ليست من مميزات التطبيق وتُطلب بشكل منفصل."/><button className="btn btn-ghost" onClick={()=>navigate('/services')}>عرض جميع الخدمات</button></div><div className="services-grid preview">{teamServices.map((s,i)=><article className="service-card" key={s.title}><div className="service-icon"><Icon name={s.icon} size={28}/></div><span className="service-index">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></div></section>}
function Performance(){return <section className="section performance-section"><div className="container"><SectionTitle eyebrow="الأداء والاعتمادية" title="OnStar لا يحوّل MikroTik إلى جهاز يشغّل التطبيق" text="تم تصميم التطبيق بحيث تبقى واجهته ومعالجة بياناته وملفاته على الهاتف، بينما يتعامل مع MikroTik فقط عند الحاجة لتنفيذ إعداد تختاره أنت." center/><div className="performance-flow"><article><span className="flow-no">01</span><img src="/app-assets/ic_onstar.png" alt="OnStar"/><h3>المعالجة داخل الهاتف</h3><p>إدارة التصاميم، ملفات الصفحة، النسخ الاحتياطي، البحث، الشروحات وقواعد بيانات التطبيق تتم داخل الهاتف.</p></article><article><span className="flow-no">02</span><img src="/app-assets/ic_mikrotik_tools.webp" alt="MikroTik"/><h3>إرسال الإعداد عند الطلب</h3><p>عند استخدام أداة MikroTik، يرسل OnStar الأوامر أو الإعدادات اللازمة عبر الاتصال بالراوتر، ثم ينتهي دور التطبيق في تلك العملية.</p></article><article><span className="flow-no">03</span><img src="/app-assets/ic_security.webp" alt="RouterOS"/><h3>RouterOS يطبق القاعدة فقط</h3><p>أي Queue أو Firewall أو Mangle تضيفها تعمل داخل RouterOS كإعداد عادي. الحمل - إن وجد - يعتمد على القاعدة وحجم الشبكة، وليس على تشغيل OnStar نفسه.</p></article></div><div className="performance-note"><b>الخلاصة:</b> لا يتم تثبيت OnStar داخل MikroTik ولا توجد عملية خلفية من التطبيق تستهلك CPU الراوتر بشكل مستمر.</div></div></section>}
function Support(){return <section className="section pocket-support"><div className="container split-layout"><div className="support-phone-card"><img src="/app-assets/ic_onstar.png" alt="OnStar"/><div><span>OnStar v3</span><strong>مساعد شبكتك في جيبك 24/7</strong><small>أدوات + إرشادات + شروحات + إدارة من الهاتف</small></div></div><div><SectionTitle eyebrow="الهدف من OnStar" title="أقل اعتمادًا على اللابتوب، وأكثر قدرة على حل المشكلة من مكانك" text="من تركيب الصفحة وإعدادها إلى التعديلات اليومية والفحص والصيانة، الهدف أن يكون صاحب الشبكة قادرًا على إنجاز العمل من هاتفه مباشرة، مع أدوات عربية واضحة وشروحات تقلل الحاجة إلى خبرة مسبقة أو أوامر MikroTik اليدوية."/><div className="check-grid">{['تعديل الصفحة من الهاتف','فحص أجهزة الشبكة','نسخ واستعادة الإعدادات','أدوات MikroTik بواجهات واضحة','دليل لكل أداة','فيديوهات شرح مرتبطة'].map(x=><span key={x}>✓ {x}</span>)}</div><p className="support-clarity">مصطلح «24/7» هنا يعني أن أدوات المساعدة الذاتية متاحة معك دائمًا داخل الهاتف، وليس وعدًا بوجود موظف دعم بشري مباشر طوال اليوم.</p></div></div></section>}
function Guide({navigate}){return <section className="section guide-preview"><div className="container"><SectionTitle eyebrow="دليل الاستخدام" title="كل أداة لها شرح واضح قبل أن تستخدمها" text="اعثر على الأداة بالاسم أو الوظيفة، وافهم ماذا تفعل وكيف تستخدمها قبل تطبيق أي تغيير." center/><div className="guide-preview-grid"><article><strong>100+</strong><span>أداة وواجهة تشغيلية</span></article><article><strong>10</strong><span>أقسام منظمة</span></article><article><strong>بحث</strong><span>بالاسم والوظيفة والتقنية</span></article></div><div className="center-action"><button className="btn btn-primary" onClick={()=>navigate('/guide')}>فتح دليل أدوات OnStar</button></div></div></section>}
function Network({navigate}){return <section className="section section-dark"><div className="container split-layout"><div><SectionTitle eyebrow="Network Manager" title="شبكتك كاملة، منظمة وقابلة للفحص" text="سجّل كل جهاز مع بياناته المهمة، ثم افحص حالته من التطبيق بدل الرجوع إلى قوائم وملفات منفصلة."/><div className="check-grid">{['IP و VLAN','النوع والمنطقة','Ping مباشر','فحص Range','إحصائيات','نسخ احتياطي'].map(x=><span key={x}>✓ {x}</span>)}</div><button className="btn btn-primary" onClick={()=>navigate('/network')}>اكتشف إدارة الشبكة</button></div><div className="dashboard-card"><div className="dash-head"><span>Network overview</span><b>Live</b></div><div className="dash-kpis"><div><strong>142</strong><small>إجمالي الأجهزة</small></div><div><strong>92%</strong><small>متصل الآن</small></div></div><div className="chart-bars">{[58,82,46,92,70,88,64,95,76].map((h,i)=><i key={i} style={{height:`${h}%`}}/> )}</div><div className="dash-legend"><span>Access Points</span><span>Antennas</span><span>Others</span></div></div></div></section>}
function Academy({navigate}){return <section className="section"><div className="container"><SectionTitle eyebrow="OnStar Academy" title="تعلم التطبيق خطوة بخطوة" text="مكتبة فيديوهات مرتبة حسب الأقسام، مع وصول مباشر إلى الشرح الذي تحتاجه." center/><div className="category-pills">{tutorialCategories.map(c=><button key={c.id} onClick={()=>navigate(`/tutorials?category=${c.id}`)}>{c.icon} {c.title}</button>)}</div><div className="tutorial-grid home-tutorials">{tutorials.slice(0,6).map(t=><TutorialCard key={t.id} item={t} category={tutorialCategories.find(c=>c.id===t.category)}/>)}</div><div className="center-action"><button className="btn btn-ghost" onClick={()=>navigate('/tutorials')}>عرض جميع الشروحات</button></div></div></section>}
function Stats(){return <section className="section stats-section"><div className="container stats-grid">{stats.map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div></section>}
function CTA(){return <section className="section"><div className="container cta-panel"><div><span className="eyebrow">مجتمع OnStar</span><h2>ابقَ قريبًا من التحديثات والشروحات</h2><p>انضم إلى مجموعة التطبيق أو تواصل مباشرة مع المطور للاستفسارات الفنية.</p></div><div className="cta-actions"><a className="btn btn-primary" href={whatsapp.group} target="_blank" rel="noreferrer">الانضمام إلى الجروب</a><a className="btn btn-ghost" href={whatsapp.developer} target="_blank" rel="noreferrer">التواصل مع المطور</a></div></div></section>}
function Custom({data}){return <section className={`section custom-section ${data.theme==='dark'?'section-dark':''}`}><div className="container">{data.image&&<div className="custom-image"><img src={data.image} alt=""/></div>}<SectionTitle eyebrow={data.eyebrow||''} title={data.title||''} text={data.text||''} center={data.center!==false}/>{data.cards?.length>0&&<div className="feature-grid">{data.cards.map((c,i)=><article className="feature-card" key={i}>{c.image&&<div className="icon-box app-icon"><img src={c.image} alt=""/></div>}<h3>{c.title}</h3><p>{c.text}</p></article>)}</div>}</div></section>}

export default function Home({navigate}){
 const builtin={hero:<Hero navigate={navigate}/>, 'brand-strip':<Brand/>, features:<Features/>,speed:<Speed/>,services:<Services navigate={navigate}/>,performance:<Performance/>,support:<Support/>,guide:<Guide navigate={navigate}/>,network:<Network navigate={navigate}/>,academy:<Academy navigate={navigate}/>,stats:<Stats/>,cta:<CTA/>}
 return <>{studio.homeSections.filter(s=>s.enabled!==false).map(s=>s.type==='custom'?<Custom key={s.id} data={studio.customSections.find(c=>c.id===s.id)||s}/>:<React.Fragment key={s.id}>{builtin[s.id]||null}</React.Fragment>)}</>
}
