import { esc, icon, url } from './utils.js';
export const A = (href, label, primary = false) => `<a class="btn ${primary ? 'btn-primary' : 'btn-outline'}" href="${esc(href)}" data-link>${label} <span>${icon('arrow', 18)}</span></a>`;
const badge = (x) => `<span class="eyebrow"><i></i>${esc(x)}</span>`;
function visual(mode = 'app') {
    const cloud = mode === 'cloud';
    return `<div class="hero-scene ${cloud ? 'cloud-scene' : 'app-scene'}" aria-label="تصور تجريدي للاتصال بأجهزة الشبكة" role="img">
 <div class="scene-grid"></div><div class="scene-orbit orbit-one"></div><div class="scene-orbit orbit-two"></div>
 <svg class="scene-paths" viewBox="0 0 680 600" aria-hidden="true"><path d="M106 150 C230 130 236 272 330 275 S515 165 585 200"/><path d="M100 435 C220 440 260 308 333 284 S508 462 605 431"/><path d="M332 280V90"/></svg>
 <div class="scene-top"><span>ONSTAR / CONNECTIVITY</span><span class="scene-live"><i></i> NETWORK EXPERIENCE</span></div>
 <div class="scene-center"><div class="scene-core"><span class="core-mark">${cloud ? icon('cloud', 55) : icon('smartphone', 55)}</span><strong>${cloud ? 'CLOUD' : 'ONSTAR'}</strong><small>${cloud ? 'REMOTE NETWORK ACCESS' : 'NETWORK CONTROL APP'}</small></div></div>
 <div class="scene-node node-a">${icon('network', 19)}<b>MikroTik</b><small>ROUTER</small></div>
 <div class="scene-node node-b">${icon('wifi', 19)}<b>Access Point</b><small>DEVICE</small></div>
 <div class="scene-node node-c">${icon('shield', 19)}<b>HotSpot</b><small>MANAGEMENT</small></div>
 <div class="scene-node node-d">${icon('settings', 19)}<b>Control</b><small>INTERFACE</small></div>
 <div class="scene-bottom"><span>01 / EXPERIENCE</span><span>ONSTAR ECOSYSTEM — 2026</span></div></div>`;
}
export function home(site) {
    const items = site.content.features || [];
    return `<section class="hero dark-surface"><div class="container hero-layout"><div class="hero-copy">${badge('منظومة ONSTAR الرقمية')}<h1>مساحة أوسع<br/>للتحكم <em>بشبكتك.</em></h1><p class="hero-lead">تجربة تجمع بين إدارة صفحة الدخول وأدوات الشبكة من هاتفك، والوصول إلى أجهزتك عن بُعد عبر خدمة سحابية مستقلة.</p><div class="hero-buttons">${A('/app', 'استكشف تطبيق OnStar', true)}${A('/remote-access', 'اكتشف OnStar Cloud')}</div><div class="hero-foot"><span><b>01</b> تطبيق إدارة الشبكة</span><span><b>02</b> خدمة الوصول عن بُعد</span></div></div>${visual()}</div><div class="hero-edge">ONSTAR <span>—</span> YOUR NETWORK. YOUR WAY.</div></section>
 <section class="section light-surface products" id="ecosystem"><div class="container"><div class="section-heading between">${badge('منتجان. منظومة واحدة.')}<h2>حدد ما تحتاجه،<br/><em>واكتشف عالمه الخاص.</em></h2></div><div class="product-duo"><a href="/app" data-link class="product-panel product-app"><div class="product-index">01 / MOBILE APPLICATION</div><div class="product-symbol">${icon('smartphone', 50)}</div><div class="product-body"><p>ONSTAR APP</p><h3>أدوات الشبكة<br/>في راحة يدك.</h3><span>إدارة HotSpot والتصميم والسرعات وإعدادات الشبكات من تطبيق Android.</span><strong>استكشف التطبيق ${icon('arrow', 20)}</strong></div></a><a href="/remote-access" data-link class="product-panel product-cloud"><div class="product-index">02 / CLOUD SERVICE</div><div class="product-symbol">${icon('cloud', 52)}</div><div class="product-body"><p>ONSTAR CLOUD</p><h3>شبكتك معك<br/>من أي مكان.</h3><span>الاشتراكات والوصول إلى أجهزة الشبكة المدعومة عبر خدمة OnStar Cloud.</span><strong>استكشف الخدمة ${icon('arrow', 20)}</strong></div></a></div></div></section>
 <section class="section editorial-section"><div class="container editorial-grid"><div><div class="kicker">THE APP EXPERIENCE — 01</div><h2>من صفحة الدخول،<br/><em>إلى تفاصيل الشبكة.</em></h2><p>اكتشف أدوات OnStar لإدارة الصفحات والسرعات والحماية والإعدادات، مع دليل استخدام مفصل لكل أداة من أدوات المشروع.</p>${A('/guide', 'تصفح دليل الأدوات', true)}</div><div class="editorial-stack"><div class="showcase-media"><img src="/media-app-settings.png" loading="lazy" alt="صورة واجهة تطبيق OnStar المرفقة مع المشروع"/><div class="media-stamp">ORIGINAL ONSTAR ASSET</div></div><div class="editorial-notes"><div><strong>${site.tools.length}</strong><span>أداة موثقة في المكتبة</span></div><div><strong>${site.tutorials.length}</strong><span>شرح فيديو في المكتبة</span></div></div></div></div></section>
 <section class="section cloud-feature dark-surface"><div class="container cloud-feature-layout"><div>${badge('ONSTAR CLOUD / ACCESS')}<h2>حتى خارج شبكتك،<br/><em>تبقى الإدارة قريبة.</em></h2><p>حساب واحد للاشتراك ومتابعة حالة الخدمة، مع عناوين الوصول الفعلية التي يتيحها السيرفر بعد اعتماد الخدمة وتجهيز الاتصال.</p>${A('/remote-access', 'تعرف على آلية العمل', true)}</div><div class="cloud-mini"><div class="cloud-mini-head">REMOTE ACCESS / CONCEPT <span>● VISUAL EXAMPLE</span></div><div class="cloud-mini-flow"><div>${icon('user', 29)}<span>أنت</span></div><b class="flow-dash">•••••••</b><div class="flow-focus">${icon('cloud', 38)}<span>OnStar Cloud</span></div><b class="flow-dash">•••••••</b><div>${icon('network', 29)}<span>الأجهزة</span></div></div><p>رسم توضيحي فقط — لا يعرض حالة اتصال حقيقية.</p></div></div></section>
 <section class="section light-surface"><div class="container"><div class="section-heading between">${badge('KNOWLEDGE / EXPERIENCE')}<h2>المعرفة،<br/><em>جزء من المنتج.</em></h2><p>دليل واحد يربط الأدوات، والشروحات، والفيديوهات، ومعلومات استخدام لوحة الأجهزة.</p></div><div class="knowledge-teasers"><a href="/knowledge?tab=tools" data-link><span>01 / TOOLS</span><strong>${site.tools.length} أداة</strong><small>خطوات استخدام وشرح تفصيلي</small>${icon('arrow', 24)}</a><a href="/knowledge?tab=videos" data-link><span>02 / VIDEOS</span><strong>${site.tutorials.length} فيديو</strong><small>مكتبة شروحات تطبيق OnStar</small>${icon('arrow', 24)}</a><a href="/knowledge?tab=cloud" data-link><span>03 / CLOUD GUIDES</span><strong>36 دليلًا</strong><small>شرح واجهات لوحة الأجهزة</small>${icon('arrow', 24)}</a></div></div></section>
 <section class="section cta-section"><div class="container cta-bar"><div><span>BUILD YOUR NEXT NETWORK EXPERIENCE</span><h2>ابدأ بالمنتج<br/>الذي يناسب شبكتك.</h2></div><div>${A('/app', 'تطبيق OnStar', true)}${A('/register', 'إنشاء حساب Cloud')}</div></div></section>`;
}
export function appPage(site) {
    const features = site.content.features || [];
    return `<section class="subhero dark-surface"><div class="container subhero-layout"><div>${badge('ONSTAR / ANDROID APPLICATION')}<h1>لوحة أدواتك.<br/><em>بذكاء هاتفك.</em></h1><p>أدوات فعلية لإدارة صفحات HotSpot والسرعات والتحديثات وإعدادات MikroTik. كل أداة موثقة لتعرف وظيفتها وطريقة استخدامها.</p><div class="hero-buttons">${A('/guide', 'استكشف الأدوات', true)}${A('/tutorials', 'شاهد الشروحات')}</div></div><div class="app-head-visual"><div class="app-device"><div class="app-device-head">${icon('wifi', 22)} <span>ONSTAR NETWORK MANAGER</span><span>•••</span></div><div class="app-device-title"><small>لوحة الشبكة</small><strong>كل ما تحتاجه<br/>لإدارة الشبكة</strong></div><div class="app-device-widgets"><div>${icon('settings', 27)}<span>إعدادات الصفحة</span></div><div>${icon('bolt', 27)}<span>السرعات</span></div><div>${icon('shield', 27)}<span>الحماية</span></div><div>${icon('network', 27)}<span>أدوات MikroTik</span></div></div><small class="app-demo-note">تصور تصميمي — ليست بيانات اتصال مباشرة</small></div></div></div></section>
 <section class="section light-surface"><div class="container"><div class="section-heading between">${badge('WHAT YOU CAN DO')}<h2>إمكانات متعددة.<br/><em>نظام واحد متكامل.</em></h2></div><div class="feature-list">${features.map((x, i) => `<article class="feature-line"><span>${String(i + 1).padStart(2, '0')}</span><h3>${esc(x.title)}</h3><p>${esc(x.text || x.description || '')}</p>${icon('arrow', 23)}</article>`).join('')}</div></div></section>
 <section class="section app-photography"><div class="container"><div class="section-heading between">${badge('ORIGINAL MEDIA')}<h2>من داخل أصول<br/><em>OnStar الأصلية.</em></h2><p>صور مرفقة مع المشروع، لا نماذج توليد وهمية للتطبيق.</p></div><div class="photo-strip"><div class="photo-main"><img src="/media-app-settings.png" loading="lazy" alt="صورة إعدادات OnStar الأصلية"/></div><div class="photo-side"><img src="/media/5888523995773079739_121.jpg" loading="lazy" alt="صورة من وسائط مشروع OnStar"/><img src="/media/5888658608638071244_121.jpg" loading="lazy" alt="صورة أخرى من وسائط OnStar"/></div></div></div></section>
 <section class="section dark-surface"><div class="container app-content-intro">${badge('EXPLORE 128 TOOLS')}<h2>ليست مجرد مميزات في قائمة.<br/><em>كل أداة لها شرحها.</em></h2><p>ابحث عن الأداة التي تحتاجها واقرأ التفاصيل والخطوات والملاحظات من مكتبة المشروع كاملة.</p><div class="app-topic-links">${site.toolCategories.slice(0, 7).map((c) => `<a href="/guide?category=${encodeURIComponent(c.id)}" data-link>${esc(c.title)} ${icon('arrow', 16)}</a>`).join('')}</div>${A('/guide', 'فتح دليل الأدوات', true)}</div></section>`;
}
export function cloudPage() {
    const steps = [['01', 'أنشئ حسابًا', 'سجل بياناتك الأساسية واسم الشبكة.'], ['02', 'أكّد بريدك الإلكتروني', 'استخدم الرمز الذي يصلك من الخدمة.'], ['03', 'اختر الباقة', 'راجع الباقات والأسعار الحقيقية من حسابك.'], ['04', 'تحقق من MikroTik', 'نفّذ كود التحقق الخاص بحسابك.'], ['05', 'أرسل طلب التجربة أو الدفع', 'المراجعة والموافقة تتمان من الإدارة.'], ['06', 'جهّز الاتصال', 'بعد اعتماد الخدمة يظهر كود إعداد VPN الخاص بك.'], ['07', 'ابدأ الوصول', 'استخدم المنافذ والعناوين المتاحة لحسابك.']];
    return `<section class="subhero dark-surface cloud-page-hero"><div class="container subhero-layout"><div>${badge('ONSTAR CLOUD / REMOTE ACCESS')}<h1>إدارة الشبكة.<br/><em>دون حدود المكان.</em></h1><p>خدمة للوصول إلى أجهزة الشبكة المدعومة من خارج الشبكة، مع حساب اشتراك ولوحة أجهزة مستقلة ومعلومات وصول مخصصة حسب الصلاحيات وحالة التفعيل.</p><div class="hero-buttons">${A('/register', 'إنشاء حساب مشترك', true)}${A('/customer-login', 'دخول المشترك')}</div><div class="hero-foot"><span>خدمة مستقلة عن تطبيق Android</span><span>تفعيل وفق حالة الحساب واعتماد الإدارة</span></div></div>${visual('cloud')}</div></section>
 <section class="section light-surface"><div class="container"><div class="section-heading between">${badge('HOW IT WORKS')}<h2>من أول خطوة،<br/><em>حتى جاهزية الاتصال.</em></h2><p>خطوات مرتبة وفق آلية خدمة OnStar Cloud الحالية. إتمام الطلب لا يعني الموافقة أو التفعيل تلقائيًا.</p></div><div class="step-grid">${steps.map(([n, t, d]) => `<div class="cloud-step"><span>${n}</span><h3>${t}</h3><p>${d}</p></div>`).join('')}</div></div></section>
 <section class="section cloud-practical"><div class="container"><div class="section-heading between">${badge('PRACTICAL WALKTHROUGH')}<h2>خطوات عملية،<br/><em>واضحة قبل التنفيذ.</em></h2><p>تعرّف على ما يفعله المشترك من الواجهة والراوتر في كل مرحلة. إعدادات الخدمة الحساسة لا تُعرض في الشروحات العامة.</p></div><div class="cloud-accordion">
 <details open><summary><span>01</span> إنشاء الحساب وتأكيد البريد</summary><ol><li>اختر إنشاء حساب مشترك، ثم اكتب بيانات الشبكة والبريد.</li><li>حدد إصدار RouterOS الصحيح، v6 أو v7.</li><li>أدخل رمز البريد لتأكيد الحساب، ثم سجّل الدخول.</li></ol><p>إذا لم يصلك الرمز استخدم خيار إعادة الإرسال دون إنشاء حساب جديد.</p></details>
 <details><summary><span>02</span> إثبات ملكية MikroTik</summary><ol><li>من حسابك افتح قسم التحقق وأنشئ كود التحقق الخاص بك.</li><li>انسخ الكود كما هو إلى Terminal في MikroTik.</li><li>بعد نجاح التنفيذ، ارجع إلى الحساب وحدّث حالة التحقق.</li></ol><p>لا يلزم كتابة الرقم التسلسلي يدويًا.</p></details>
 <details><summary><span>03</span> اختيار الباقة والتجربة والدفع</summary><ol><li>راجع الأسعار والباقات المعروضة من السيرفر.</li><li>قدّم طلب التجربة إذا أظهر حسابك أهلية فعلية، أو اختر باقة لإنشاء فاتورة.</li><li>بعد الإيداع أرسل تفاصيل العملية وأرفق الإيصال إن وجد.</li></ol><p>لا يتم تشغيل الخدمة أو اعتماد الدفع أو بدء التجربة بمجرد تقديم الطلب.</p></details>
 <details><summary><span>04</span> إعداد اتصال VPN</summary><ol><li>بعد الموافقة وتجهيز الخدمة، افتح قسم التحقق والاتصال بحسابك.</li><li>اعرض كود VPN المخصص من السيرفر وانسخه إلى MikroTik.</li><li>نفّذ الكود وتحقق من نجاح الاتصال، ثم حدّث معلومات الوصول في حسابك.</li></ol></details>
 <details><summary><span>05</span> منافذ API وFTP وSSH</summary><ol><li>تحقق من منافذ الخدمات الداخلية في إعدادات MikroTik.</li><li>من حسابك افتح قسم الوصول والمنافذ.</li><li>أدخل المنافذ الداخلية الصحيحة واضغط حفظ ومزامنة.</li></ol><p>لا تخلط بين المنفذ الداخلي في الراوتر والمنفذ الخارجي المخصص للحساب.</p></details>
 <details><summary><span>06</span> استخدام معلومات الوصول ولوحة الأجهزة</summary><ol><li>بعد تفعيل الخدمة استخدم عناوين الوصول الظاهرة في حسابك.</li><li>يمكن نسخ عناوين ومنافذ خدمات الإدارة المدعومة بحسب تجهيز شبكتك.</li><li>عندما يوفر لك السيرفر رابط لوحة الأجهزة، افتحه واستخدم بيانات دخوله الخاصة.</li><li>يدعم التطبيق جلب بعض معلومات اتصال OnStar Cloud من الحساب وفق الإمكانات المتاحة.</li></ol><p>لا يرسل الموقع كلمات مرور MikroTik إلى التطبيق، وتبقى صلاحيات إدارة الأجهزة خاضعة للخادم.</p></details>
 </div></div></section>
 <section class="section editorial-section"><div class="container cloud-real-grid"><div>${badge('BUILT FOR NETWORK OPERATORS')}<h2>الأجهزة المختلفة،<br/><em>واجهة إدارة واحدة.</em></h2><p>الوصول إلى MikroTik ونقاط الوصول TP-Link وUbiquiti وNanoStation وOpenWrt وأجهزة البث المدعومة؛ تتحدد الوظائف والخدمات المفعلة بحسب التجهيزات والصلاحيات.</p><div class="protocols">${['MikroTik', 'TP-Link', 'Ubiquiti', 'NanoStation', 'OpenWrt', 'Access Points', 'WinBox', 'SSH', 'FTP', 'API'].map(x => `<span>${x}</span>`).join('')}</div></div><div class="cloud-topology"><div class="topology-title">NETWORK ACCESS <span>CONCEPT DEMO</span></div><div class="topology-user">${icon('user', 33)} <span>العميل</span></div><div class="topology-connector"></div><div class="topology-core">${icon('cloud', 43)}<b>OnStar Cloud</b></div><div class="topology-connector"></div><div class="topology-devices"><span>${icon('network', 22)}<small>Router</small></span><span>${icon('wifi', 22)}<small>AP</small></span><span>${icon('settings', 22)}<small>Devices</small></span></div><p>محاكاة تعريفية فقط. حالة الأجهزة الحقيقية تُقرأ من لوحة المشترك عند تفعيل الخدمة.</p></div></div></section>
 <section class="section light-surface"><div class="container"><div class="section-heading between">${badge('ACCOUNT & SUBSCRIPTION')}<h2>اشتراكك ومعلومات الوصول،<br/><em>في مكان واحد.</em></h2></div><div class="benefit-grid"><article><span>${icon('credit', 30)}</span><h3>فواتير وطلبات واضحة</h3><p>تابع الباقات وحالة الطلبات والفواتير وإثباتات الدفع من حسابك.</p></article><article><span>${icon('shield', 30)}</span><h3>تجربة بعد الموافقة</h3><p>الطلب لا يبدأ التجربة. يظهر القرار والحالة من السيرفر بعد مراجعة الإدارة.</p></article><article><span>${icon('network', 30)}</span><h3>إدارة الأجهزة</h3><p>انتقل إلى لوحة أجهزتك المخصصة واستخدم الخيارات المتاحة لحسابك.</p></article></div></div></section>
 <section class="section dark-surface"><div class="container cta-bar dark-cta"><div><span>READY TO CONNECT?</span><h2>ابدأ بخطوة واحدة.<br/>أنشئ حسابك.</h2></div><div>${A('/register', 'إنشاء حساب جديد', true)}${A('/knowledge?tab=cloud', 'دليل استخدام Cloud')}</div></div></section>`;
}
export function servicesPage(site) { return `<section class="simple-hero dark-surface"><div class="container">${badge('PROFESSIONAL SERVICES')}<h1>خبرة تقنية.<br/><em>تنفيذ حسب احتياجك.</em></h1><p>أعمال تنفيذ الشبكات والتخصيص والاستشارات الفنية التي يقدمها الفريق بشكل مستقل عن التطبيق والاشتراك.</p></div></section><section class="section light-surface"><div class="container"><div class="service-list">${site.content.teamServices.map((s, i) => `<article><span>${String(i + 1).padStart(2, '0')}</span><div><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p></div>${icon('arrow', 25)}</article>`).join('')}</div><div class="service-contact">${A('/contact', 'تواصل مع الفريق', true)}</div></div></section>`; }
export function contactPage(site) { const target = url(site.whatsapp?.developer), group = url(site.whatsapp?.group); return `<section class="simple-hero dark-surface"><div class="container">${badge('GET IN TOUCH')}<h1>لنبدأ حوارًا<br/><em>عن شبكتك.</em></h1><p>للاستفسار عن تطبيق OnStar أو خدمة OnStar Cloud أو الخدمات البرمجية، استخدم قنوات التواصل الرسمية.</p></div></section><section class="section light-surface"><div class="container contact-container"><h2>قنوات التواصل</h2>${target ? `<a class="contact-link" href="${esc(target)}" rel="noopener noreferrer" target="_blank">تواصل مع فريق التطوير عبر WhatsApp ${icon('external', 22)}</a>` : '<p>لم يتم تحديد رابط رسمي للتواصل داخل بيانات الموقع.</p>'}${group ? `<a class="contact-link" href="${esc(group)}" rel="noopener noreferrer" target="_blank">مجتمع OnStar والشروحات والتحديثات ${icon('external', 22)}</a>` : ''}<p>للاستفسارات الخاصة بحساب Cloud استخدم قنوات الدعم المتاحة في حسابك، ولا ترسل كلمات مرور الأجهزة.</p></div></section>`; }
export function faqPage(site) { return `<section class="simple-hero dark-surface"><div class="container">${badge('FAQ / SUPPORT')}<h1>أسئلة شائعة،<br/><em>وإجابات واضحة.</em></h1></div></section><section class="section light-surface"><div class="container faq-list">${site.content.faqs.map((f) => `<details><summary>${esc(Array.isArray(f) ? f[0] : (f.q || f.question || f.title))}</summary><p>${esc(Array.isArray(f) ? f[1] : (f.a || f.answer || f.text))}</p></details>`).join('')}</div></section>`; }
export function notFound() { return `<section class="simple-hero dark-surface"><div class="container"><span class="eyebrow">404 / PAGE NOT FOUND</span><h1>هذا المسار<br/><em>غير موجود.</em></h1><p>يمكنك العودة للصفحة الرئيسية أو البحث في مركز المعرفة.</p>${A('/', 'الصفحة الرئيسية', true)} ${A('/knowledge', 'مركز المعرفة')}</div></section>`; }
// Original deep links remain real, separately re-imagined content experiences.
// Legacy demo IP / device status values were deliberately not brought into production.
export function featuresPage(site) {
    const items = site.content.speedMethods || [];
    return `${simpleIntro('ONSTAR / CAPABILITIES', 'أدوات عملية.<br/><em>من صفحة الدخول إلى الشبكة.</em>', 'تعرّف على القدرات الموثقة في تطبيق OnStar وخيارات اختيار السرعات المناسبة لتكوين شبكتك.')}
 <section class="section light-surface"><div class="container"><div class="section-heading between"><span class="eyebrow">ONSTAR / FEATURES</span><h2>أدوات متعددة.<br/><em>مصممة للعمل الفعلي.</em></h2></div><div class="feature-list">${site.content.features.map((f, i) => `<article class="feature-line"><span>${String(i + 1).padStart(2, '0')}</span><h3>${esc(f.title)}</h3><p>${esc(f.text)}</p>${icon('arrow', 22)}</article>`).join('')}</div></div></section>
 <section class="section editorial-section"><div class="container"><div class="section-heading between"><span class="eyebrow">FIVE SPEED STRATEGIES</span><h2>خمس طرق<br/><em>للتحكم بالسرعات.</em></h2><p>تختلف الطرق بحسب الحاجة إلى Domain وهيكل Queue وHotSpot الموجود لديك.</p></div><div class="method-grid">${items.map((m, i) => `<article><span>${String(i + 1).padStart(2, '0')}</span><h3>${esc(m.title)}</h3><p>${esc(m.text)}</p></article>`).join('')}</div><div class="method-foot">يمكنك من إعدادات التطبيق تحويل صفحة الدخول بين وضع تحديد السرعة والوضع بدون تحديد سرعة دون إعادة إنشائها بالكامل.</div></div></section><section class="section dark-surface"><div class="container app-content-intro"><h2>كل أداة،<br/><em>موثقة بالتفصيل.</em></h2><p>انتقل إلى المكتبة واستكشف الخطوات والملاحظات والارتباط بالشروحات.</p>${A('/guide', 'مكتبة الأدوات', true)}</div></section>`;
}
function simpleIntro(k, t, d) { return `<section class="simple-hero dark-surface"><div class="container"><span class="eyebrow"><i></i>${esc(k)}</span><h1>${t}</h1><p>${esc(d)}</p></div></section>`; }
export function networkPage(site) {
    const fields = site.content.deviceFields || [];
    const features = [['سجل أجهزة الشبكة', 'تنظيم أجهزة الشبكة حسب رقم الجهاز ونوعه والمنطقة وعنوان IP والمعلومات المتاحة.'], ['فحص Ping', 'استعلام عن الأجهزة المتصلة أو غير المستجيبة من الأجهزة المسجلة.'], ['فحص مدى IP', 'البحث عن الأجهزة المستجيبة داخل نطاق IP تختاره.'], ['الوصول بين القطاعات', 'استخدام أدوات الشبكة الموثقة للوصول إلى الأجهزة بحسب تصميم VLAN والشبكة.']];
    return `${simpleIntro('ONSTAR / NETWORK MANAGER', 'سجل أجهزتك.<br/><em>وأدر تفاصيل شبكتك.</em>', 'توثيق الأجهزة والفحص والبحث والإحصائيات، ضمن أدوات إدارة الشبكة المرتبطة بتطبيق OnStar.')}
 <section class="section light-surface"><div class="container"><div class="section-heading between"><span class="eyebrow">DEVICE REGISTRY</span><h2>المعلومات المهمة،<br/><em>في سجل واحد.</em></h2><p>هذه الحقول مأخوذة من وصف أدوات إدارة الشبكة في الموقع السابق.</p></div><div class="device-fields">${fields.map((f) => `<span>${icon('check', 18)}${esc(f)}</span>`).join('')}</div><div class="method-grid">${features.map((item, i) => `<article><span>${String(i + 1).padStart(2, '0')}</span><h3>${item[0]}</h3><p>${item[1]}</p></article>`).join('')}</div>${A('/guide?category=network', 'شروحات إدارة الشبكة', true)}</div></section>`;
}
export function mikrotikPage(site) {
    const features = [['السرعات', 'طرق تشمل Simple Queue وPCQ وQueue Tree وHotSpot، مع خيارات تستخدم Domain أو تعمل بدونه.'], ['الحماية', 'أدوات HotSpot وDNS وبعض أنواع الحماية المتاحة بحسب إعداد الشبكة.'], ['User Manager', 'أدوات الصيانة وجدولة حذف الكروت المنتهية وإدارة المستخدمين.'], ['الوصول إلى الأجهزة', 'تسهيل العمل مع أجهزة Access Point وغيرها من أجهزة الشبكة.']];
    return `${simpleIntro('ONSTAR / MIKROTIK TOOLKIT', 'وظائف MikroTik.<br/><em>من مكان واحد.</em>', 'مجموعة أدوات مساعدة مصممة للبيئات القائمة على MikroTik، مع شروحات مباشرة لتطبيقها.')}
 <section class="section light-surface"><div class="container"><div class="method-grid">${features.map((f, i) => `<article><span>${String(i + 1).padStart(2, '0')}</span><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div>${A('/guide?category=mikrotik', 'عرض أدوات MikroTik', true)}</div></section>
 <section class="section editorial-section"><div class="container"><div class="section-heading between"><span class="eyebrow">SPEED ENGINE</span><h2>اختر أسلوب السرعة<br/><em>الذي يناسب شبكتك.</em></h2></div><div class="method-grid">${site.content.speedMethods.map((m, i) => `<article><span>${String(i + 1).padStart(2, '0')}</span><h3>${esc(m.title)}</h3><p>${esc(m.text)}</p></article>`).join('')}</div></div></section>`;
}
export function updatesPage(site) {
    return `${simpleIntro('ONSTAR / RELEASE NOTES', 'تحديثات OnStar.<br/><em>رحلة التطوير مستمرة.</em>', 'التغييرات والميزات الموثقة في إصدارات تطبيق OnStar.')}
 <section class="section light-surface"><div class="container release-list">${site.content.updates.map((u) => `<article><div><span>${esc(u.date)}</span><h2>${esc(u.version)}</h2></div><ul>${(u.items || []).map((i) => `<li>${icon('check', 17)} ${esc(i)}</li>`).join('')}</ul></article>`).join('')}</div></section>`;
}
