import {readFileSync,readdirSync,existsSync,statSync} from 'node:fs';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const read=(path)=>readFileSync(join(root,path),'utf8');
const content=JSON.parse(read('public/content/site_content.json'));
const guides=JSON.parse(read('public/content/platform_guides.json'));
const files=[];function walk(p){for(const f of readdirSync(join(root,p),{withFileTypes:true})){const r=join(p,f.name);if(f.isDirectory())walk(r);else files.push(r)}}walk('src');walk('scripts');
for(const p of files.filter(x=>x.endsWith('.js')||x.endsWith('.mjs')))execFileSync(process.execPath,['--check',join(root,p)]);
const assert=(x,msg)=>{if(!x)throw new Error('FAIL: '+msg);console.log('PASS: '+msg)};
assert(content.tools.length===128,'128 original tool records retained');
assert(content.tutorials.length===35,'35 original video records retained');
assert(guides.platformGuides.length===36,'36 original platform guides retained');
assert(content.content.faqs.length===11,'11 FAQs retained');
assert(content.content.teamServices.length===4,'4 team services retained');
assert(new Set(content.tools.map(x=>x.slug)).size===128,'tool slugs unique');
assert(new Set(guides.platformGuides.map(x=>x.id)).size===36,'guide IDs unique');
assert(content.tutorials.every(t=>/^[-\w]{11}$/.test(t.videoId)),'all source videos have YouTube IDs');
assert(content.tools.filter(t=>(t.steps||[]).length).length===127,'127 tools have source steps; 1 original tool has no steps (documented gap)');
assert(guides.platformGuides.every(g=>(g.steps||[]).length),'every platform guide has steps');
const all=files.filter(x=>x.endsWith('.js')).map(read).join('\n');
const needed=['/me','/config','/plans','/register','/login','/logout','/email/verify','/email/resend','/password/forgot','/password/reset','/order','/trial/request','/router/verification-token','/router/setup-script','/router/connection-ports','/payment-confirmations'];
assert(needed.every(x=>all.includes(`'${x}'`)),'16 legacy API endpoints preserved');
assert(read('src/api.js').includes("credentials:'include'"),'session cookie credentials included');
assert(!all.includes('localStorage'),'no localStorage tokens or authentication hints');
assert(read('netlify.toml').includes('https://vpn.onstareh.com/v2/customer-api/:splat'),'original Netlify proxy destination preserved');
assert(read('netlify.toml').includes('from = "/api/customer/*"'),'original Netlify API path preserved');
assert(read('netlify.toml').indexOf('from = "/api/customer/*"')<read('netlify.toml').indexOf('from = "/*"'),'API reverse proxy precedes SPA fallback');
assert(existsSync(join(root,'public/media-app-settings.png')),'real source app screenshot retained');
assert(files.filter(x=>x.endsWith('.js')).every(x=>!read(x).includes('innerHTML = response')),'no naive API response raw HTML injection');
assert(!existsSync(join(root,'public/.env'))&&!existsSync(join(root,'.env')),'no environment secrets files');
assert(existsSync(join(root,'index.html'))&&existsSync(join(root,'src/styles/style.css')),'new design entry and tokenized stylesheet present');
console.log('VALIDATION PASS — static contract and integrity checks. Live API and visual browser tests NOT performed.');
